name: m64p
base: core20
version: "v2021.12.3"
compression: lzo
summary: An easy to use N64 emulator. Available for Windows and Linux
description: |
  m64p uses mupen64plus-gui, a brand new mupen64plus frontend written in Qt5. It supports all of the things you’d expect from a frontend (savestate management, pausing, screenshots, etc.).

  m64p comes bundled with paraLLEl-RDP for graphics. It should give you the best out-of-the-box experience available for N64 gaming.
grade: stable
confinement: strict

layout:
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0

apps:
  m64p:
    command: mupen64plus/mupen64plus-gui
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - audio-playback
      - audio-record
      - screen-inhibit-control
      - joystick
      - hidraw
    environment:
      DISABLE_WAYLAND: 1
      M64P_DISABLE_UPDATER: 1
      VK_ICD_FILENAMES: "/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json"

parts:
  m64p:
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libhidapi-hidraw0
      - libminizip1
      - p7zip-full
      - libatomic1
      - libglu1-mesa
      - libvulkan1
      - mesa-vulkan-drivers
      - libvulkan-dev
    override-prime: |
      snapcraftctl prime
      cp -f $SNAPCRAFT_STAGE/usr/lib/p7zip/7za $SNAPCRAFT_STAGE/usr/bin/7za
    source: https://github.com/loganmc10/m64p/releases/download/v2021.12.3/m64p-linux64-2ae80db.zip
    plugin: dump
